apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-cp-manage
  namespace: staging-finance
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    #nginx.ingress.kubernetes.io/rewrite-target: /finance/
    nginx.ingress.kubernetes.io/app-root: /finance
spec:
  ingressClassName: nginx
  rules:
  - host: finance.foxvspig.com
    http:
      paths:
      - backend:
          service:
            name: svc-cp-manage
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - finance.foxvspig.com
    secretName: ingress-for-cp-manage
